---
title: "Detergent-Free Membrane Protein Purification Using SMA Polymer"
format: html
description: A review of methods for resuspending membrane proteins in SMALPs
date-format: iso
date: 2022-07-01
---

In my postdoctoral research, I spent a great deal of time and effort improving the process of producing purified sample of our protein of interest, ABCG2. For a lot of experiments, membrane proteins need to be resuspended in aqueous solution (slightly salty water). The proteins don't like being by themselves in these solutions, so need to either take a bit of membrane with them or something to mimic it. In the past, this was often detergent (fancy, very expensive soap), which often required testing a lot of detergents (again, expensive), and made the environment that the protein was in less like its normal home.

Researchers had the idea of adding small amounts of a polymer called styrene-maleic acid (SMA) to membrane preparations. This polymer likes to form rings, and when added to samples of membrane, makes a ring with little samples of membrane inside. This seemed pretty magical, as suddenly there was a cheap material that would produce solubilized membrane proteins in a closer analogue to their native environment, and seemed to work every time. The picture has got a bit more complicated since, as you may need to test a few different SMA derivatives, but it's still a really useful method.

When I started working with SMA lipid particles (SMALPs), we wanted to get samples of pure ABCG2, and not have too many SMALPs with other membrane proteins along for the ride. My predecessor in the lab was using a method that produced samples that were about 70% ABCG2. Eventually, after a lot of optimization, I managed to get comparable yields, but with undetectable amounts of anything else. The main obstacle to this was discovering that free molecules of SMA that hadn't gone into making SMALPs interfered with the purification process. I tried lots of ways of removing it, ending up with a method that uses what is essentially a tiny, very fine sieve. My favourite method was one where you just added SMA to cells. The yield wasn't as high, but it was really cool that you could just add the polymer directly, without any other steps. The slight problem was that the DNA from the cells was released, which is sticky, and ended up tangling up a load of protein. There were signs that adding an enzyme that digests DNA could help, but we didn't have time or money to get it working. We think the reason it did work was that there wasn't much free SMA, as it was soaked up by all the cell membranes that we normally got rid of when preparing membranes.

After all that work, it turned out that SMALP solubilized ABCG2 didn't quite behave in a way that would work with the experiments we needed solubilised ABCG2 for and we had to change our approach. Still, we contributed the method we used to this methods paper, which covers lots of the tricks needed to get good SMALPs

[DOI: 10.1007/978-1-0716-2368-8_21](https://doi.org/10.1007/978-1-0716-2368-8_21)